# Generated by Django 3.2.7 on 2022-04-28 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventdocument',
            options={'verbose_name': "document lié à l'évènement", 'verbose_name_plural': "documents liés à l'évènement"},
        ),
        migrations.AddField(
            model_name='attendee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Date d'inscription"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.event', verbose_name='Évènement'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'Abandonné'), (0, 'Inscrit'), (1, 'Non sélectionné'), (2, 'Sélectionné'), (3, 'Accepté'), (4, 'Confirmé')], verbose_name='Statut de la candidature'),
        ),
        migrations.AlterField(
            model_name='center',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='center',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True, verbose_name='Longitude'),
        ),
    ]
