# Generated by Django 3.2.7 on 2022-04-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20220428_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, help_text="Ce texte, si défini, est affiché lors de l'inscription à l'évènement (il peut éventuellement contenir des liens)", null=True, verbose_name='Notes'),
        ),
    ]
