# Generated by Django 3.2.7 on 2022-05-17 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='address',
        ),
        migrations.RemoveField(
            model_name='center',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='center',
            name='lng',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.IntegerField(blank=True, null=True, verbose_name='Numéro de voie')),
                ('street_name', models.CharField(max_length=200, verbose_name='Nom de la voie')),
                ('complement', models.CharField(blank=True, max_length=200, null=True, verbose_name="Complément d'adresse")),
                ('city', models.CharField(max_length=50, verbose_name='Ville')),
                ('zip_code', models.IntegerField(verbose_name='Code postal')),
                ('country', models.CharField(default='France', max_length=30, verbose_name='Pays')),
                ('center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.center', verbose_name='Centre')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
            },
        ),
    ]
