# Generated by Django 3.2.7 on 2022-05-10 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20220510_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.center', verbose_name='Centre'),
        ),
    ]
