# Generated by Django 3.2.7 on 2022-05-10 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20220510_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='center',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.center', verbose_name='Centre'),
        ),
    ]
