# Generated by Django 4.1.4 on 2022-12-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0004_alter_partner_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
    ]
