# Generated by Django 4.2 on 2023-06-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "events",
            "0002_remove_application_labels_application_address_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (-3, "Candidature rejetée"),
                    (-2, "Candidature annulée de la part de la candidate"),
                    (-1, "Candidature annulée de la part des organisateurs"),
                    (0, "Candidature en cours de traitement"),
                    (1, "Candidature acceptée"),
                    (2, "Candidature confirmée"),
                    (3, "Stage terminé"),
                ],
                default=0,
                verbose_name="Statut de la candidature",
            ),
        ),
    ]
