# Generated by Django 4.2 on 2023-05-30 04:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="year",
            field=models.PositiveIntegerField(
                default=2022,
                verbose_name="Année de l'événement",
            ),
            preserve_default=False,
        ),
    ]
