# Generated by Django 4.2 on 2023-05-30 04:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_event_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="form",
        ),
    ]
