# Generated by Django 3.2.7 on 2022-12-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_auto_20220820_1854"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="camps_type",
            field=models.CharField(
                choices=[("long", "Stage Long"), ("short", "Stage Court")],
                default="Stage Court",
                max_length=256,
                verbose_name="Durée du stage",
            ),
            preserve_default=False,
        ),
    ]
