# Generated by Django 4.2 on 2023-05-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_application_about_application_allergies_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="about",
        ),
        migrations.RemoveField(
            model_name="application",
            name="allergies",
        ),
        migrations.RemoveField(
            model_name="application",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="application",
            name="diet",
        ),
        migrations.RemoveField(
            model_name="application",
            name="learning",
        ),
        migrations.RemoveField(
            model_name="application",
            name="programming",
        ),
        migrations.RemoveField(
            model_name="application",
            name="studies",
        ),
        migrations.RemoveField(
            model_name="application",
            name="tshirt",
        ),
        migrations.AddField(
            model_name="application",
            name="form_answer",
            field=models.JSONField(
                default=dict, verbose_name="Réponse de formulaire"
            ),
        ),
    ]
