# Generated by Django 4.2 on 2023-05-31 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_remove_application_about_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023,
                    5,
                    31,
                    21,
                    28,
                    45,
                    70827,
                    tzinfo=datetime.timezone.utc,
                ),
                verbose_name="Date d'inscription",
            ),
            preserve_default=False,
        ),
    ]
