# Development Dockerfile

FROM node:18 AS base

ENV DEBIAN_FRONTEND=noninteractive \
    LC_ALL=C.UTF-8 \
    LANG=C.UTF-8 \
    NODE_OPTIONS=--openssl-legacy-provider

RUN userdel node
ARG NODE_UID=1000
ARG NODE_GID=1000


RUN mkdir -p /app && \
    useradd -d /app -r -u ${NODE_UID} app && \
    chown app:${NODE_GID} -R /app

WORKDIR /app

USER app:${NODE_GID}

COPY ./entrypoint.sh ./entrypoint.sh
COPY ./tsconfig.json ./tsconfig.json
COPY ./nuxt.config.js ./nuxt.config.js
COPY ./yarn.lock ./yarn.lock
COPY ./package.json ./package.json
RUN yarn install

ENTRYPOINT ["/app/entrypoint.sh"]
