from .common import *  # noqa

SOCIAL_AUTH_PROLOGIN_KEY = "CHANGE_ME"

SOCIAL_AUTH_PROLOGIN_SECRET = "CHANGE_ME"

AWS_S3_ENDPOINT_URL = "CHANGE_ME"

AWS_STORAGE_BUCKET_NAME = "gcc-site-dev"

AWS_ACCESS_KEY_ID = "CHANGE_ME"

AWS_SECRET_ACCESS_KEY = "CHANGE_ME"
