# Generated by Django 4.2.2 on 2023-09-15 16:12

import django.core.validators
from django.db import migrations, models

import gccsite.storages
import partners.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "website_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL du site"
                    ),
                ),
                (
                    "logo",
                    models.FileField(
                        storage=gccsite.storages.GCCMediaStorage,
                        upload_to=partners.models.Partner.upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "gif"]
                            )
                        ],
                        verbose_name="Logo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Promoted", "Partenaires qui nous soutiennent"),
                            ("Funding", "Partenaires qui nous financent"),
                            ("Welcoming", "Partenaires qui nous accueillent"),
                        ],
                        default="Promoted",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partenaire",
                "verbose_name_plural": "Partenaires",
            },
        ),
    ]
