# Generated by Django 4.2.2 on 2023-08-10 20:53

import django.core.validators
from django.db import migrations, models

import gccsite.storages
import partners.models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0005_alter_partner_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="logo",
            field=models.FileField(
                storage=gccsite.storages.GCCMediaStorage,
                upload_to=partners.models.Partner.upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "gif"]
                    )
                ],
                verbose_name="Logo",
            ),
        ),
    ]
