# Generated by Django 4.2.7 on 2023-11-26 17:55

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': [('manage_applications', 'Can manage the status of applications'), ('override_applications', 'Can override the application status flow')], 'verbose_name': 'candidatures', 'verbose_name_plural': 'candidatures'},
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-3, 'Candidature rejetée'), (-2, 'Candidature annulée par la candidate'), (-1, 'Candidature annulée par les organisateurs'), (0, 'Candidature en cours de traitement'), (1, 'Candidature acceptée'), (2, 'Candidature confirmée'), (3, 'Stage terminé')], default=0, protected=True, verbose_name='Statut de la candidature'),
        ),
    ]
