# Generated by Django 4.2.7 on 2023-12-10 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_options_alter_application_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='dob',
            new_name='birthdate',
        ),
    ]
