# Generated by Django 4.2.7 on 2023-12-12 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
        ('applications', '0003_rename_dob_application_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='address',
        ),
        migrations.RemoveField(
            model_name='application',
            name='address_resp',
        ),
        migrations.RemoveField(
            model_name='application',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='application',
            name='email',
        ),
        migrations.RemoveField(
            model_name='application',
            name='email_resp',
        ),
        migrations.RemoveField(
            model_name='application',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='first_name_resp',
        ),
        migrations.RemoveField(
            model_name='application',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='last_name_resp',
        ),
        migrations.RemoveField(
            model_name='application',
            name='nb_participations',
        ),
        migrations.RemoveField(
            model_name='application',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='application',
            name='phone_resp',
        ),
        migrations.RemoveField(
            model_name='application',
            name='school',
        ),
        migrations.AddField(
            model_name='application',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name="Profile de l'utilisateur"),
            preserve_default=False,
        ),
    ]
