# Generated by Django 4.2.7 on 2023-12-18 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_application_event_remove_application_user_and_more'),
        ('profiles', '0001_initial'),
        ('applications', '0004_remove_application_address_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('event', 'profile')},
        ),
    ]
