# Generated by Django 4.2.7 on 2024-01-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_application_notes_alter_application_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='tshirt',
            field=models.CharField(choices=[(None, '-'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='M', max_length=3, verbose_name='Taille de tshirt'),
            preserve_default=False,
        ),
    ]
