# Generated by Django 4.2.7 on 2024-01-29 00:59

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_application_tshirt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=django_fsm.FSMField(choices=[('rejected', 'Candidature rejetée'), ('withdrawn', 'Candidature annulée par la candidate'), ('cancelled', 'Candidature annulée par les organisateurs'), ('pending', 'Candidature en cours de traitement'), ('accepted', 'Candidature acceptée'), ('confirmed', 'Candidature confirmée'), ('ended', 'Stage terminé')], default='pending', max_length=50, protected=True, verbose_name='Statut de la candidature'),
        ),
    ]
