FROM node:14 AS builder

WORKDIR /app
COPY package.json /app
COPY yarn.lock /app
RUN chown -R 1000:1000 /app
USER 1000
RUN yarn install

COPY . /app
RUN NODE_ENV=production yarn run build
#TODO: remove *.map, tree-shaking and merge js files?

FROM nginx
COPY --from=builder /app/dist/ /usr/share/nginx/html/
