# Generated by Django 4.2 on 2023-05-31 21:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="date_last_interaction",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_archived",
        ),
    ]
