# Generated by Django 4.2.2 on 2023-06-17 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_date_last_interaction_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_view_applications", "Can view event applications"),
                    (
                        "can_view_applications_details",
                        "Can view details of event applications",
                    ),
                    (
                        "can_view_applications_private_details",
                        "Can view private details of event applications",
                    ),
                    ("can_change_applications", "Can change applications"),
                    (
                        "can_download_informations",
                        "Can download applications informations",
                    ),
                ]
            },
        ),
    ]
