# Generated by Django 4.2.7 on 2023-12-12 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nom de famille')),
                ('birth_date', models.DateField(verbose_name='Date de naissance')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email de la participante')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Numéro de téléphone de la participante')),
                ('address', models.JSONField(default=dict, verbose_name='Adresse de la participante')),
                ('nb_participations', models.IntegerField(blank=True, default=0, null=True, verbose_name='Nombre de participations')),
                ('school', models.JSONField(default=dict, verbose_name='Établissement scolaire de la participante')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Profile du responsable')),
            ],
        ),
    ]
