# Generated by Django 4.2.7 on 2024-04-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_applications', 'Can view event applications'), ('can_view_applications_details', 'Can view details of event applications'), ('can_view_applications_private_details', 'Can view private details of event applications'), ('can_change_applications', 'Can change applications'), ('can_download_informations', 'Can download applications informations'), ('respo-idf', 'Responsable of IDF region')]},
        ),
    ]
