# Generated by Django 4.2.7 on 2023-12-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='responsable',
        ),
    ]
