# Generated by Django 4.2.7 on 2023-12-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Établissement scolaire de la participante'),
        ),
    ]
