# Generated by Django 4.2.7 on 2023-12-13 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur lié'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.JSONField(default=dict, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nb_participations',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=16, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Établissement scolaire'),
        ),
    ]
