[tool.poetry]
name = "gccsite-api"
version = "0.1.0"
description = "Backend of Girls Can Code! website"
authors = ["Association Prologin <info@prologin.org>"]
license = "AGPL-3.0"

[tool.poetry.dependencies]
python = "^3.10"
boto3 = "^1.24"
celery = { version = "^5.2" }
django = "^4.2"
gunicorn = "^20.1.0"
ipython = "^8.12.0"
psycopg2-binary = "^2.9.6"
django-crispy-forms = "^2.0"
crispy-bootstrap5 = "^0.7"
django-bootstrap-icons = "^0.8.3"
django-structlog = { version = "^4.0", extras = [ "celery" ] }
django-storages = "^1.12"
django-redis = { version = "^5" }
django-rest-knox = { version = "^4.2" }
django-celery-beat = { version = "^2.4"}
django-debug-toolbar = "*"
django-mail-panel = "^4.0"
django-post-office = "^3.6"


[tool.poetry.dev-dependencies]
black = "*"
isort = "*"
pre-commit = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79
