# Generated by Django 4.2.2 on 2023-09-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('year',), 'verbose_name': 'évènement', 'verbose_name_plural': 'évènements'},
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default='migration_null', max_length=254, verbose_name='Adresse email de la participante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='email_resp',
            field=models.EmailField(default='migration_null', max_length=254, verbose_name='Adresse email du responable légal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='first_name_resp',
            field=models.CharField(default='migration_null', max_length=256, verbose_name='Prénom du responsable légal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='last_name_resp',
            field=models.CharField(default='migration_null', max_length=256, verbose_name='Nom du responsable légal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='nb_participations',
            field=models.CharField(default='', verbose_name='Nombre de participations de la participante'),
        ),
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.TextField(default='migration_null', verbose_name='Notes sur la candidatures'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='phone_resp',
            field=models.CharField(blank=True, max_length=16, verbose_name='Numéro de téléphone du responsable légal'),
        ),
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.JSONField(default=dict, verbose_name='Adresse de la participante'),
        ),
        migrations.AlterField(
            model_name='application',
            name='address_resp',
            field=models.JSONField(default=dict, verbose_name='Adresse du responsable légal'),
        ),
        migrations.AlterField(
            model_name='application',
            name='dob',
            field=models.DateField(verbose_name='Date de naissance de la participante'),
        ),
        migrations.AlterField(
            model_name='application',
            name='first_name',
            field=models.CharField(max_length=256, verbose_name='Prénom de la participante'),
        ),
        migrations.AlterField(
            model_name='application',
            name='last_name',
            field=models.CharField(max_length=256, verbose_name='Nom de la participante'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, max_length=16, verbose_name='Numéro de téléphone de la participante'),
        ),
    ]
