# Generated by Django 4.2 on 2023-06-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="labels",
        ),
        migrations.AddField(
            model_name="application",
            name="address",
            field=models.JSONField(
                default=dict,
                verbose_name="Adresse partielle de la participante",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (-3, "Candidature rejetée"),
                    (-2, "Candidature annulée de la part de la candidate"),
                    (-1, "Candidature annulée de la part des organisateurs"),
                    (0, "Candidature en cours de traitement"),
                    (1, "Candidature acceptée"),
                    (2, "Candidature confirmée"),
                    (3, "Stage terminé"),
                ],
                verbose_name="Statut de la candidature",
            ),
        ),
    ]
