# Generated by Django 4.2.2 on 2023-06-17 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="notes",
            field=models.TextField(
                default="", verbose_name="Notes sur la candidatures"
            ),
            preserve_default=False,
        ),
    ]
