# Generated by Django 4.2.7 on 2023-11-16 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_application_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='event',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.DeleteModel(
            name='ApplicationLabel',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
