# Generated by Django 4.2.2 on 2023-06-10 17:35

import django.core.validators
from django.db import migrations, models
import events.validators
import gccsite.storage.backends


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventdocument",
            name="document",
        ),
        migrations.RemoveField(
            model_name="eventdocument",
            name="event",
        ),
        migrations.RemoveField(
            model_name="event",
            name="documents",
        ),
        migrations.AddField(
            model_name="event",
            name="document",
            field=models.FileField(
                blank=True,
                null=True,
                storage=gccsite.storage.backends.PrivateMediaStorage,
                upload_to="events_gcc/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("pdf",)
                    ),
                    events.validators.validate_is_pdf,
                ],
            ),
        ),
        migrations.DeleteModel(
            name="Document",
        ),
        migrations.DeleteModel(
            name="EventDocument",
        ),
    ]
