# Generated by Django 4.2.2 on 2023-09-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_application_address_resp"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="gg_maps_query",
            field=models.TextField(
                blank=True,
                max_length="100",
                null=True,
                verbose_name="Query Google Maps",
            ),
        ),
    ]
