# Generated by Django 4.2.7 on 2023-12-25 08:57

import django.core.validators
from django.db import migrations, models
import events.validators


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_application_event_remove_application_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='eventdocument',
            name='event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='documents',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='EventDocument',
        ),
        migrations.AddField(
            model_name='event',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='events_gcc/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf',)), events.validators.validate_is_pdf], verbose_name='Documents'),
        ),
    ]
