# Generated by Django 4.2.2 on 2023-09-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "events",
            "0003_application_email_resp_application_first_name_resp_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ("year",),
                "verbose_name": "évènement",
                "verbose_name_plural": "évènements",
            },
        ),
        migrations.AddField(
            model_name="application",
            name="email",
            field=models.EmailField(
                default="example@prologin.org",
                max_length=254,
                verbose_name="Adresse email de la participante",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="phone_resp",
            field=models.CharField(
                blank=True,
                max_length=16,
                verbose_name="Numéro de téléphone du responsable légal",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=16,
                verbose_name="Numéro de téléphone de la participante",
            ),
        ),
    ]
