# Generated by Django 4.2 on 2023-06-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_application_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="form",
        ),
        migrations.AddField(
            model_name="application",
            name="phone",
            field=models.CharField(
                blank=True, max_length=16, verbose_name="Numéro de téléphone"
            ),
        ),
        migrations.DeleteModel(
            name="Form",
        ),
    ]
