# Generated by Django 4.2.2 on 2023-09-07 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_address_gg_maps_query"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="address",
            name="lng",
        ),
    ]
