# Generated by Django 4.2.7 on 2024-01-20 22:59

import django.core.validators
from django.db import migrations, models
import events.validators


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='events_gcc/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf',)), events.validators.validate_is_pdf, events.validators.FileSizeValidator(10)], verbose_name='Documents'),
        ),
    ]
