# Generated by Django 4.2.7 on 2024-04-26 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_alter_event_documents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('year',), 'permissions': [('can_manage_event', 'Can manage all events'), ('can_be_event_manager', 'Can become event manager'), ('can_be_event_staff', 'Can become event staff')], 'verbose_name': 'évènement', 'verbose_name_plural': 'évènements'},
        ),
        migrations.AddField(
            model_name='event',
            name='managers',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Managers'),
        ),
        migrations.AddField(
            model_name='event',
            name='staff',
            field=models.ManyToManyField(blank=True, null=True, related_name='staffed_events', to=settings.AUTH_USER_MODEL, verbose_name='Staffs'),
        ),
    ]
