# Generated by Django 4.2 on 2023-04-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="city",
        ),
        migrations.RemoveField(
            model_name="user",
            name="country",
        ),
        migrations.RemoveField(
            model_name="user",
            name="zip_code",
        ),
        migrations.AddField(
            model_name="user",
            name="newsletter_subscribed",
            field=models.BooleanField(default=False),
        ),
    ]
