# Generated by Django 4.1.4 on 2023-01-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_review',
            field=models.BooleanField(default=False, verbose_name='Droit de review'),
        ),
    ]
