# Generated by Django 4.1.4 on 2023-01-03 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_review_applications', 'Can review the applications to a camps')]},
        ),
    ]
