# Generated by Django 4.2 on 2023-05-10 18:44

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_address_remove_user_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.TextField()),
                ("zip_code", models.TextField(max_length=5)),
                ("city", models.TextField()),
                (
                    "country",
                    django_countries.fields.CountryField(
                        default="FR", max_length=2, verbose_name="Pays"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                auto_now=True, verbose_name="Date de naissance"
            ),
        ),
    ]
