# Generated by Django 4.2 on 2023-05-15 21:03

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_address_remove_user_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Birth date"
            ),
        ),
    ]
