# Generated by Django 4.2 on 2023-05-10 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_address_user_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.address",
            ),
        ),
    ]
