# Generated by Django 4.2 on 2023-05-10 19:14

import django.db.models.deletion
from django.db import migrations, models

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.ForeignKey(
                default=users.models.Address.get_default_address,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.address",
            ),
        ),
    ]
