# Generated by Django 4.2 on 2023-05-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(verbose_name="Date de naissance"),
        ),
    ]
