files: .*
exclude: "(gccsite/.*/migrations/.*|gccsite/gccsite/settings/.*)"
repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: ["--count", "--ignore=E731,W503", "--show-source", "--statistics"]
