# Generated by Django 4.2.7 on 2023-12-16 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nom de famille')),
                ('birth_date', models.DateField(verbose_name='Date de naissance')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Numéro de téléphone')),
                ('address', models.JSONField(default=dict, verbose_name='Adresse')),
                ('nb_participations', models.IntegerField(blank=True, default=0, null=True, verbose_name='Nombre')),
                ('school', models.JSONField(blank=True, default=dict, null=True, verbose_name='Établissement scolaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
    ]
