# Generated by Django 4.2.7 on 2023-12-16 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='Prénom de la participante')),
                ('last_name', models.CharField(max_length=256, verbose_name='Nom de la participante')),
                ('birth_date', models.DateField(verbose_name='Date de naissance de la participante')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email de la participante')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Numéro de téléphone de la participante')),
                ('street_app', models.CharField(max_length=64, verbose_name='Nom et numéro de voie')),
                ('complement_app', models.CharField(blank=True, max_length=64, verbose_name="Complément d'adressse (si nécessaire)")),
                ('city_app', models.CharField(max_length=64, verbose_name='Ville')),
                ('zipcode_app', models.CharField(max_length=16, verbose_name='Code postal')),
                ('country_app', models.CharField(max_length=32, verbose_name='Pays')),
                ('first_name_resp', models.CharField(max_length=256, verbose_name='Prénom du responsable légal')),
                ('last_name_resp', models.CharField(max_length=256, verbose_name='Nom du responsable légal')),
                ('email_resp', models.EmailField(default='', max_length=254, verbose_name='Adresse email du responable légal')),
                ('phone_resp', models.CharField(blank=True, max_length=16, verbose_name='Numéro de téléphone du responsable légal')),
                ('street_resp', models.CharField(max_length=64, verbose_name='Nom et numéro de voie')),
                ('complement_resp', models.CharField(blank=True, max_length=64, verbose_name="Complément d'adressse (si nécessaire)")),
                ('city_resp', models.CharField(max_length=64, verbose_name='Ville')),
                ('zipcode_resp', models.CharField(max_length=16, verbose_name='Code postal')),
                ('country_resp', models.CharField(max_length=32, verbose_name='Pays')),
                ('school_name', models.CharField(max_length=64, verbose_name='Etablissement scolaire de la participante')),
                ('street_school', models.CharField(max_length=64, verbose_name='Nom et numéro de voie')),
                ('complement_school', models.CharField(blank=True, max_length=64, verbose_name="Complément d'adressse (si nécessaire)")),
                ('city_school', models.CharField(max_length=64, verbose_name='Ville')),
                ('zipcode_school', models.CharField(max_length=16, verbose_name='Code postal')),
                ('country_school', models.CharField(max_length=32, verbose_name='Pays')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
    ]
