# Generated by Django 4.2.7 on 2024-04-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Statut validation email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_resp_confirmed',
            field=models.BooleanField(default=False, verbose_name='Statut validation email responsable legal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_resp',
            field=models.EmailField(default='', max_length=254, verbose_name='Adresse email du responsable légal'),
        ),
    ]
