# Generated by Django 4.2.7 on 2023-12-16 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nb_participations',
        ),
        migrations.AddField(
            model_name='profile',
            name='address_resp',
            field=models.JSONField(default=dict, verbose_name='Adresse du responsable légal'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_resp',
            field=models.EmailField(default='', max_length=254, verbose_name='Adresse email du responable légal'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name_resp',
            field=models.CharField(default='', max_length=256, verbose_name='Prénom du responsable légal'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name_resp',
            field=models.CharField(default='', max_length=256, verbose_name='Nom du responsable légal'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_resp',
            field=models.CharField(blank=True, max_length=16, verbose_name='Numéro de téléphone du responsable légal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.JSONField(default=dict, verbose_name='Adresse de la participante'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(verbose_name='Date de naissance de la participante'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adresse email de la participante'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=256, verbose_name='Prénom de la participante'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=256, verbose_name='Nom de la participante'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=16, verbose_name='Numéro de téléphone de la participante'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.JSONField(default=dict, verbose_name='Etablissement scolaire de la participante'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
