# Generated by Django 4.2.13 on 2024-05-13 16:59

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='complement_app',
            field=models.CharField(blank=True, max_length=64, verbose_name="Complément d'adressse (facultatif)"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='complement_resp',
            field=models.CharField(blank=True, max_length=64, verbose_name="Complément d'adressse (facultatif)"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='complement_school',
            field=models.CharField(blank=True, max_length=64, verbose_name="Complément d'adressse (facultatif)"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country_app',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country_resp',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country_school',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='FR', verbose_name='Numéro de téléphone de la participante'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_resp',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='FR', verbose_name='Numéro de téléphone du responsable légal'),
        ),
    ]
